# ref: http://wiki.ros.org/diff_drive_controller

hardware_interface:
   joints: 
    - left_whell
    - right_whell

diff_controller:

    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'left_whell'
    right_wheel : 'right_whell'
    publish_rate: 50.0

    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    # wheel_separation : 0.47 legacy
    wheel_separation : 0.53
    # wheel_radius : 0.1016 # 8 polegadas
    wheel_radius : 0.1046 # 8 polegadas ajustado

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0
    
    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25

    # Base frame_id
    base_frame_id: robot_base_footprint #default: base_link
    enable_odom_tf: false #true: encoders | false: needs ekf to publish
    
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.4  # m/s
        min_velocity           : -0.4 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.001  # m/s^2
        min_acceleration       : -0.001 # m/s^2
        # has_jerk_limits        : true
        # max_jerk               : 25  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.8  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 0.001 # rad/s^2
        min_acceleration       : -0.001 # rad/s^2
        # has_jerk_limits        : true
        # max_jerk               : 6.5  # rad/s^3
  
  